// examples/nextjs/app/components/SearchResults.tsx
import type { SearchResult } from 'boox'
import type { Pokemon } from '../types'
import SearchResultComponent from './SearchResult'

interface SearchResultsProps {
  results: SearchResult<Pokemon>[]
}

const SearchResults: React.FC<SearchResultsProps> = ({ results }) => {
  return (
    <div
      id='results'
      className={`list-group list-group-flush overflow-auto rounded-3 ${
        results.length ? 'd-block' : 'd-none'
      }`}
    >
      {results.map(result => (
        <SearchResultComponent key={result.id} result={result} />
      ))}
    </div>
  )
}

export default SearchResults

// examples/vue/src/components/SearchResults.vue
<template>
  <div
    id="results"
    class="list-group list-group-flush overflow-auto rounded-3"
    :class="{ 'd-none': !results.length }"
  >
    <SearchResult v-for="result in results" :key="result.id" :result="result" />
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import type { Result } from '../types'
import SearchResult from './SearchResult.vue'

export default defineComponent({
  components: {
    SearchResult
  },
  props: {
    results: {
      type: Array as () => Result[],
      required: true
    }
  }
})
</script>
