// examples/react/src/components/Search.tsx
import { useState, useEffect } from 'react'
import Boox, { type SearchResult } from 'boox'
import { useDebounce } from 'use-debounce'
import type { Pokemon } from '../types'
import SearchInfo from './SearchInfo'
import SearchResults from './SearchResults'

const DEBOUNCE_DELAY = 300
const PLACEHOLDER_TEXT = 'Search (e.g. pikachu, water pwer)'

interface SearchProps {
  model: Boox<Pokemon>
}

const Search: React.FC<SearchProps> = ({ model }) => {
  const [input, setInput] = useState('')
  const [results, setResults] = useState<SearchResult<Pokemon>[]>([])
  const [query] = useDebounce(input, DEBOUNCE_DELAY)

  useEffect(() => {
    const performSearch = async () => {
      if (!query) {
        setResults([])
        return
      }

      const searchResults = await model.search(query)
      setResults(searchResults)
    }

    performSearch()
  }, [model, query])

  const totalDocuments = Object.keys(model.currentState.documents).length

  return (
    <>
      <form id='search-form' className='p-3' role='search'>
        <div className='form-group'>
          <input
            type='search'
            className='form-control form-control-lg'
            id='search-query'
            placeholder={PLACEHOLDER_TEXT}
            aria-label='Search pokemons'
            autoFocus
            value={input}
            onChange={e => setInput(e.target.value)}
          />

          <div className='form-text'>
            <strong>Note:</strong>
            <span> the </span>
            <code className='bg-body-secondary'>pwer</code>
            <span> demonstrates a typing error for </span>
            <code className='bg-body-secondary'>power</code>.
          </div>
        </div>
      </form>

      <SearchInfo results={results} totalDocuments={totalDocuments} />
      <SearchResults results={results} />
    </>
  )
}

export default Search

// examples/vue/src/components/Search.vue
<template>
  <form id="search-form" class="p-3" role="search">
    <div class="form-group">
      <input
        type="search"
        class="form-control form-control-lg"
        id="search-query"
        placeholder="Search (e.g. pikachu, water pwer)"
        aria-label="Search pokemons"
        autoFocus
        v-model.debounce.300ms="query"
      />

      <div class="form-text">
        <strong>Note:</strong>
        <span> the </span>
        <code class="bg-body-secondary">pwer</code>
        <span> demonstrates a typing error for </span>
        <code class="bg-body-secondary">power</code>.
      </div>
    </div>
  </form>

  <SearchInfo :results="results" :documents="model.currentState.documents" />

  <SearchResults :results="results" />
</template>

<script lang="ts">
import { defineComponent, ref, watch } from 'vue'
import Boox from 'boox'
import type { Pokemon, Result } from '../types'
import SearchInfo from './SearchInfo.vue'
import SearchResults from './SearchResults.vue'

export default defineComponent({
  components: {
    SearchInfo,
    SearchResults
  },
  props: {
    model: {
      type: Boox<Pokemon>,
      required: true
    }
  },
  setup(props) {
    const query = ref('')
    const results = ref<Result[]>([])

    watch(
      query,
      async newQuery => {
        if (newQuery) {
          const searchResults = await props.model.search(newQuery)

          results.value = searchResults.map(result => {
            const {
              id,
              image_url,
              name: image_alt,
              hp
            } = result.attributes as unknown as Pokemon

            return {
              id,
              image_url,
              image_alt,
              hp,
              name: result.context('name').text,
              set_name: result.context('set_name').text,
              caption: result.context('caption', 80).text
            }
          })
        } else {
          results.value = []
        }
      },
      { immediate: false } // Perform search on initial render
    )

    return { query, results }
  }
})
</script>
