// examples/nextjs/app/components/SearchInfo.tsx
import type { SearchResult } from 'boox'
import type { Pokemon } from '../types'

interface SearchInfoProps {
  results: SearchResult<Pokemon>[]
  totalDocuments: number
}

const SearchInfo: React.FC<SearchInfoProps> = ({ results, totalDocuments }) => {
  const { length } = results

  return (
    <p
      id='results-length'
      className={`px-3 text-muted ${length ? '' : 'd-none'}`}
    >
      {length ? `Found ${length} of ${totalDocuments} pokemons` : ''}
    </p>
  )
}

export default SearchInfo

// examples/svelte/src/lib/SearchInfo.svelte
<script lang="ts">
  import type { SearchResult } from 'boox'
  import type { Pokemon } from '../types'

  export let results: SearchResult<Pokemon>[] = []
  export let totalDocuments: number = 0
</script>

{#if results.length}
  <p id="results-length" class="px-3 text-muted">
    Found {results.length} of {totalDocuments} pokemons
  </p>
{/if}
