// examples/vue/src/components/SearchInfo.vue
<template>
  <p
    id="results-length"
    class="px-3 text-muted"
    :class="{ 'd-none': !results.length }"
  >
    {{
      results.length
        ? `Found ${results.length} of ${Object.keys(documents).length} pokemons`
        : ''
    }}
  </p>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import type { Documents } from 'boox'
import type { Pokemon, Result } from '../types'

export default defineComponent({
  props: {
    results: {
      type: Array as () => Result[],
      required: true
    },
    documents: {
      type: Object as () => Documents<Pokemon>,
      required: true
    }
  }
})
</script>

// examples/nextjs/app/components/SearchInfo.tsx
import type { SearchResult } from 'boox'
import type { Pokemon } from '../types'

interface SearchInfoProps {
  results: SearchResult<Pokemon>[]
  totalDocuments: number
}

const SearchInfo: React.FC<SearchInfoProps> = ({ results, totalDocuments }) => {
  const { length } = results

  return (
    <p
      id='results-length'
      className={`px-3 text-muted ${length ? '' : 'd-none'}`}
    >
      {length ? `Found ${length} of ${totalDocuments} pokemons` : ''}
    </p>
  )
}

export default SearchInfo
