// examples/svelte/src/lib/Search.svelte
<script lang="ts">
  import Boox, { type SearchResult } from 'boox'
  import { onMount } from 'svelte'
  import debounce from 'debounce'
  import { metaphone } from 'metaphone'
  import { stemmer } from 'stemmer'
  import { removeStopwords } from 'stopword'
  import type { Pokemon } from '../types'
  import SearchInfo from './SearchInfo.svelte'
  import SearchResults from './SearchResults.svelte'

  let pokemons: Pokemon[] = []
  let totalDocuments: number = 0
  let results: SearchResult<Pokemon>[] = []
  let query = ''

  const boox = new Boox<Pokemon>({
    features: ['name', 'caption', 'set_name'],
    attributes: ['hp', 'image_url'],
    modelOptions: {
      tokenizer(input) {
        return removeStopwords(Array.from(input.match(/\b\w+\b/g) || []))
      },
      stemmer: stemmer,
      phonetic: metaphone
    }
  })

  onMount(async () => {
    pokemons = await fetchData()
    await boox.addDocuments(pokemons)

    totalDocuments = Object.keys(boox.currentState.documents).length
  })

  const performSearch = debounce(async () => {
    results = await boox.search(query)
  }, 300)

  async function fetchData(): Promise<Pokemon[]> {
    try {
      const response = await fetch(
        'https://stilearning.com/boox/demo/datasets/pokemon-100r.json',
        { cache: 'default' }
      )
      return await response.json()
    } catch (error) {
      throw error
    }
  }
</script>

<form id="search-form" class="p-3" role="search">
  <div class="form-group">
    <input
      name="search"
      type="search"
      class="form-control form-control-lg"
      bind:value={query}
      on:input={performSearch}
      placeholder="Search (e.g. pikachu, water pwer)"
      aria-label="Search pokemons"
    />

    <div class="form-text">
      <strong>Note:</strong>
      the
      <code class="bg-body-secondary">pwer</code>
      demonstrates a typing error for
      <code class="bg-body-secondary">power</code>.
    </div>
  </div>
</form>

<SearchInfo bind:results bind:totalDocuments />

<SearchResults bind:results />

// examples/react/src/components/Search.tsx
import { useState, useEffect } from 'react'
import Boox, { type SearchResult } from 'boox'
import { useDebounce } from 'use-debounce'
import type { Pokemon } from '../types'
import SearchInfo from './SearchInfo'
import SearchResults from './SearchResults'

const DEBOUNCE_DELAY = 300
const PLACEHOLDER_TEXT = 'Search (e.g. pikachu, water pwer)'

interface SearchProps {
  model: Boox<Pokemon>
}

const Search: React.FC<SearchProps> = ({ model }) => {
  const [input, setInput] = useState('')
  const [results, setResults] = useState<SearchResult<Pokemon>[]>([])
  const [query] = useDebounce(input, DEBOUNCE_DELAY)

  useEffect(() => {
    const performSearch = async () => {
      if (!query) {
        setResults([])
        return
      }

      const searchResults = await model.search(query)
      setResults(searchResults)
    }

    performSearch()
  }, [model, query])

  const totalDocuments = Object.keys(model.currentState.documents).length

  return (
    <>
      <form id='search-form' className='p-3' role='search'>
        <div className='form-group'>
          <input
            type='search'
            className='form-control form-control-lg'
            id='search-query'
            placeholder={PLACEHOLDER_TEXT}
            aria-label='Search pokemons'
            autoFocus
            value={input}
            onChange={e => setInput(e.target.value)}
          />

          <div className='form-text'>
            <strong>Note:</strong>
            <span> the </span>
            <code className='bg-body-secondary'>pwer</code>
            <span> demonstrates a typing error for </span>
            <code className='bg-body-secondary'>power</code>.
          </div>
        </div>
      </form>

      <SearchInfo results={results} totalDocuments={totalDocuments} />
      <SearchResults results={results} />
    </>
  )
}

export default Search
